samples:
    SRR8608074: "data/samples/SRR8608074_R1.fastq.gz"
fn_gtf : "data/gencode.v48.primary_assembly.annotation.gtf"
fa_in : 'data/GRCh38.primary_assembly.genome.fa'
exon_name : "data/gencode.v48.primary_assembly_exons_no_first_exon.bed"
intron_name : "data/gencode.v48.primary_assembly_introns.bed"
BOWTIE2_RDNAIDX : "data/GRCh38.primary_assembly.rDNA.bowtie2_index/GRCh38.primary_assembly.rDNA"
BOWTIE2IDX : "data/GRCh38.primary_assembly.genome.bowtie2_index/GRCh38.primary_assembly.genome"
home : "/mnt/liuq/test/singularity"